### ISSUE TITLE
Fable2Typescript backend

### ISSUE THREAD

**Issue by ncave** [fsprojects/Fable#104]
@alfonsogarciacaro I'm sure you have already done some exploration of it, the question was even mentioned on [F# Weekly #13](https://sergeytihon.wordpress.com/2016/03/27/f-weekly-13-2016/), so is there a plan to add TypeScript as emitter when [#5595](https://github.com/Microsoft/TypeScript/issues/5595) lands in TypeScript 2.0?

**Comment by fdcastel** [comment]
We should put this into the FAQ :smile: -- I asked Alfonso the same thing some weeks ago.

I'll let him to give you a better answer, but the short version is Babel have more friendly interfaces (like [do expressions](http://babeljs.io/docs/plugins/transform-do-expressions/)) which makes the job easier. [TypeScript/#5595](https://github.com/Microsoft/TypeScript/issues/5595) is just a part of what is needed.

That said, you can use Fable-generated code with TypeScript today using es2015 modules (via `--module es2015` from command line or `"module": "es2015"` in fableconfig.json)

**Comment by alfonsogarciacaro** [comment]
Yes, it seems there's interest in this and I should probably add it to the FAQ. Basically, TypeScript was my first option when thinking about evolving FunScript and [I asked the TS team about that](https://github.com/Microsoft/TypeScript/issues/1514). However, as it was not possible to compile directly from an AST (expected for TS 2.0 but not officially confirmed) I explored other options and Babel proved to be a perfect fit.

Even if TS 2.0 supports compilation from an AST, as Fabio pointed out changing the code won't be trivial. First, TypeScript's AST is very complicated and not well documented (Babel on the other hand has the whole AST documented in a [single document](https://github.com/babel/babel/blob/master/doc/ast/spec.md)). I know because I had to struggle with it to write the ts2fable parser (which still needs some work). Also, Babel is compatible with the [do expressions](http://wiki.ecmascript.org/doku.php?id=strawman:do_expressions) ES7 proposal which makes compilation from an expression-based language like F# much simpler.

In any case, what would be your interest in compiling to TypeScript? Is it because you prefer the TypeScript pipeline or to make the interaction with other TS code easier? As Fabio suggests you can interact with compiled Fable code from TS as you would with any other JS module. If you want to do it in a more typed manner, maybe we could focus in generating TS definition files instead, which should be an easier task to implement.

**Comment by ncave** [comment]
Thank you for explaining in detail. Some reasons to add another emitter besides Babel could be if TS pipeline would perform better (faster) as claimed, or if it was somehow easier to map the type system, but I see your point about the AST complexity. In any case the whole point is to stay in F# as much as possible, so the back-end does not seem that important as long as it performs and integrates well. So looking forward to a F#-to-wasm compiler one day, if those speed-up claims are true :)

**Comment by davidpodhola** [comment]
Hi, we are currently approaching two projects that are to be written in TypeScript. We are about to deliver functions or React components to be consumed by TypeScript. My approach to this is obviously to use Fable, generate JavaScript and use it in TypeScript, but I struggle with the latest step. Don't you please have a working sample of how to use Fable-generated es2015 modules from TypeScript? Thanks!

**Comment by alfonsogarciacaro** [comment]
@davidpodhola This is going to change a bit in the next major version, but right now I would probably approach the problem in the following way:

1. Create two folders in your project for the F# and Typescript code (say, `/fsharp` and `/typescript`)
2. Add a subfolder in the Typescript directory that will become the `outDir` in fableconfig.json (e.g, `/typescript/fable`)
3. Add the `allowJs` option to your tsconfig.json. In fableconfig.json use `module: es2015` (this is default, so you can just omit the option) and if you want, `ecma: es2015`.
4. Build your F# project and check where Fable has put the files (sometimes the folders change a bit to prevent conflicts). For example, your `/fsharp/lib/Helpers.js` may become `/typescript/fable/lib/Helpers.fs`
5. All the public functions or values of the root module in your F# file become ES2015 exports in JS, so if you have a function `let add x y = x + y` you can import it from a JS/Typescript file using `import { add } from "./fable/lib/Helpers"`
6. Profit! The Fable-generated JS files will become part of your Typescript project so you can transform or bundle them according to your needs.

You can also set `declaration: true` in fableconfig and Fable will try to generate `.d.ts` so you can get type information when importing the functions from Typescript. However please note this feature is still experimental so it may be buggy, and it's not a priority at the moment, so any improvement would have to come from contributions.

Please tell me if the workflow above works for you. Have fun!

**Comment by davidpodhola** [comment]
Thanks @alfonsogarciacaro , that is exactly the workflow I was trying. I now tried to create [a really simple example](https://github.com/davidpodhola/Fable2Typescript-backend-samples) and I am getting [exactly the same error](https://github.com/davidpodhola/Fable2Typescript-backend-samples/issues/1) I got on the bigger project.

![capture](https://cloud.githubusercontent.com/assets/436605/23459624/80c1b04a-fe81-11e6-81c6-30d365bbae4c.PNG)


Anyway I will try `declaration: true` too, was not working for me earlier today and also I would be happy to contribute. We are using [Fable](http://fable.io) in the production for almost a year and that is the smallest way how to thank you for creating it.

Please advise, I am probably just missing something very obvious.

**Comment by alfonsogarciacaro** [comment]
@davidpodhola Happy to hear that! We need a testimonial place in the web 😄 

Could you please also post the F# code? Although, in the linked repo it seems the Fable code is bundled and this is probably the problem. Sorry, I thought it was clear in the instructions (I've updated them) you didn't need to bundle. Can you please try again without bundling?

> It would be possible to bundle the F# code, but I think in that case you need to choose: `"rollup": { "format": "es" }` and also you can only import the functions of the last file in your project. For your use case I think it's better to do the bundling together with the Typescript files.

**Comment by davidpodhola** [comment]
OK,  thanks a lot, now the sample works!

[included the F# code](https://github.com/davidpodhola/Fable2Typescript-backend-samples/tree/master/Client), it is just from the sample; the problem was the bundling.

So this allows me to produce JavaScript functions that would be consumed in TypeScript, that is very cool.
