### ISSUE TITLE
Partial functions have wrong values

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#115]
It looks like partial functions are sharing variable names / overwriting values which means when they are called they get the last value:

```F#
let log a b = printf "a = %s, b = %s" a b
let items = [log "First Message"; log "Second Message"]
items |> List.iter(fun x -> x "From List Iter")
```

Expected ouput:
```
a = First Message, b = From List Iter
a = Second Message, b = From List Iter
```
Actual output:
```
a = Second Message, b = From List Iter
a = Second Message, b = From List Iter
```

**Comment by davidtme** [comment]
A second example without the list:
```f#
let log a b = printf "a = %s, b = %s" a b
let item1 = log "item1"
let item2 = log "item2"
item1 "item1"
 ```

Expected ouput:
```
a = item1, b = item1
```
Actual output:
```
a = item2, b = item1
```

**Comment by alfonsogarciacaro** [comment]
As always, thanks a lot for checking the code generated by Fable so thoroughly and providing such detailed feedback, @davidtme! This proved to be trickier than I thought. The problem here is the second closure is overriding the variable of the first one, so when this is called the variable (the partially applied argument) retains the last value.

I tried to use `let` instead of `var` to declare the variables, however this was causing some unidentified problems with Babel and I had no other than way [_patching_ the problem](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Fable2Babel.fs#L217-L222). In any case, it seems to work. If it doesn't for you, just tell me.
