### ISSUE TITLE
f# functions change their calling pattern when put into records

### ISSUE THREAD

**Issue by bilkusg** [fsprojects/Fable#125]
### Description
I suspect this is by design, but if so I'd like to understand why, and perhaps have an explanation in the docs.

If I write a simple function in f#

    let jsfunc1 a b  = a +1 

the resulting javascript is a function of two arguments

    var f1 = exports.f1 = function(a, b) {
       return a + b;
    }

But if I then enclose f1 in an object using createObj ( or a statically typed record type )

    var f1obj = createObj [ "strange" ==> f1 ]    
 
i get

    var f1obj = exports.f1obj = {
        strange: function (a) {
            return function (b) {
                return f1(a, b);
            };
        }
    };

showing that the function is now a curryable version. So in dynamic code I would write

    f1 $ ( 1 , 2)

but 
  
    f1obj$strange $ 1 $ 2

to invoke

Why the difference?
There's a comment in the docs about:

    If a method accepts a lambda make sure to use System.Func
    in the signature to force the compiler uncurry any lambda passed as parameter.

and indeed if I cast f1 

    var f1obj = createObj [ "strange" ==> Func<int,int,int> f1 ]    
 
I get what I expected i.e. a function of two parameters.

But I don't understand why the default behaviour is to transform the function.

**Comment by alfonsogarciacaro** [comment]
There are two dynamics at work here: the transformations done by the F# compiler when creating the AST and those made by Fable (I actually discovered most of the former by trial and error). I'll try to summarise them here:

- Functions defined as members of a class or a module are represented in the F# AST as "normal" .NET/C# methods no matter if they have curried or tuples arguments (or both). I think this is for performance and to make interaction with C# easier. And it also works pretty well for JS compilation.

```fsharp
module MyModule
let f1 x y = x + y

// AST representation, in pseudo-C# to show the contrast
// static class MyModule {
//   public static int f1(int x, int y) { return x + y; }
// }
```

- When the functions are called with all the arguments they also look like "normal" OOP calls. However if they're called with partial arguments, the F# compiler will wrap the call in a lambda (Fable tries to optimise most common cases of this, particularly pipe chaining).

```fsharp
let test() =
   let x = f1 5 5
   let f2 = f1 8
   f2 2

// public static int test() {
//    var x = f1(5, 5);
//    var f2 = x => f1(8, 2);
//    return f2(2);
// }
```

- When you define a lambda within a method it is created with actual F# semantics instead. That is, if it has curried arguments, it'll appear in the F# AST (before any Fable compilation) as nested lambdas. And if it has tupled arguments, it will accept an actual tuple (which Fable translates as JS arrays). If you make a reference to a method as in your example (`let f1obj = createObj [ "strange" ==> f1 ]`) the F# compiler also wraps the call to make sure it'll behave semantically as a F# lambda.

```fsharp
let test2() =
   let f3 x y = x + y
   let f4 = fun (x, y) -> x + y
   let f5 = f1
   f5 5 5

// public static int test() {
//    var f3 = x => y => x + y;
//    var f4 = (Tuple<int,int> tuple) => tuple.Item1 + tuple.Item2;
//    var f5 = x => y => f1(x, y);
//    return f5(x)(y);   // Note how the arguments are being applied this time
// }
```

Please note that everything above describes how the F# compiler works (Fable hasn't come into play yet). At one point I tried to compile lambdas defined within a method as "normal" JS functions too, for simplicity and to make interoperation easier, but this soon proved to be unmanageable as it made many scenarios (like function composition) behave unexpectedly.

Now the problem obviously is you want to pass F# lambdas to JS code and they way to call the arguments (when there's more than one) is different. This problem also happens when interacting between F# and C# and the way to solve it is to convert the F# lambda to a C# delegate (`System.Func<>`). This is the same you need to do when interacting with JS in Fable. When you pass the lambda directly to a method accepting `System.Func<>` this is done automatically by the compiler in a transparent way to the user. But in other cases (like in your example where you assign the call wrapped in a lambda to a dynamic object) you need to do it explicitly. Please note that, as an optimisation, Fable makes the conversion for _anonymous lambdas_ at compile time.


I hope this makes sense, please tell me if there's anything that's unclear. Also, thanks a lot for your comments and bug reports. They're immensely valuable to improve the compiler. Keep them coming!

**Comment by bilkusg** [comment]
Thanks for such a clear and detailed explanation.

In general, I think this is a classic example of how entirely sensible low-level decisions can have confusing high-level consequences. 

After a bit more playing around, I've realised that the conversion to a curried method takes place just on a copy of the function name. So:

    let f1 a b = a + b // becomes f1(a,b)
    let f2 = f1 // becomes f2 = function(a) { return function(b) { return f1(a,b);};}

I really do think that's confusing enough to count as a bug even if it's caused by an F# design decision rather than a Fable one.

Anyway - to summarize the current behaviour to check I've got it right

* Functions defined inside another scope are always curried.
* By default, functions defined at top level and invoked with all their parameters are not curried and 
translate into javascript methods with multiple arguments - convenient for interop with Javascript
* Almost any action on a top-level function, such as putting it into a field in some type, or even just copying it at top level as a function, will silently convert it to a curried version unless somewhere on the way it gets cast to a delegate
* If the function is only used internally, you probably won't notice, because F# knows whether it's dealing with a curried version and adapts calls appropriately.
* But if you are expecting the function call to interop with non F# code, then you need to be aware when automatic currying takes place  and if that's not what you want/need, ensure that the function will be cast to a delegate, either by always passing it to somewhere which expects a delegate in its type signature or explicitly casting it.

If you have a function which you want to never be curried, you can  define it like this:

    let f1nevercurry = Func<_,_,_> (fun a b ->
         a + b
    )

    let callit = f1nevercurry.Invoke(2,5)

and then you can just pass it around as an object which translates into a normal javascript function. But this is ugly.

If you have a function which you want always to be curried then you can define it like this

    let f1curriedalready = 
         let x a b = a + b
         x

which is slightly less ugly


### Suggested solution
* If you can confirm that my understanding is now correct, I'm happy to have a go at updating the docs so that at least it's not a surprise for people. This has the advantage of being quick.
* I would love to see a new attribute which could be applied to a function to make its curried/not curried behaviour explicit and sticky. So 
    [\<curried=true\>] 
    let f1 a b = a + b // function(a) {function(b) .....

    [\<curried=false\>]
   let f2 a b = a + b // function(a,b) { .... 

where the second version would never silently curry itself ( just like the delegate implementation )
* I do think there's a case for making the default to curry everything unless its in an imported class definition. If you don't care about java interop it won't make that much difference to your program's efficiency and will prevent possible surprises. And if you do care about java interop, there would be some nice attributes to allow you to say exactly what you mean.

**Comment by alfonsogarciacaro** [comment]
> If you can confirm that my understanding is now correct, I'm happy to have a go at updating the docs so that at least it's not a surprise for people. This has the advantage of being quick.

Yes, your understanding is basically correct and I think updating the docs is a nice idea. I would just include basic information to avoid confusing users and redirect them to this issue if they need more info. Something like adding a "Calling F# code from JS" section to `interacting.md` with a text similar to the following paragraph and some examples may work:

_Any public method of a module or type can be called "normally" from JS. However, if you pass a F# lambda to JS code (even if the lambda is just a reference to a module/type method) make sure you convert it to a delegate first (e.g._ `System.Func<_,_,_>(fun x y -> x + y)` _) the same way as when interacting with C# code. When passing the lambda to a method accepting a delegate this conversion is done automatically for you._

> I would love to see a new attribute which could be applied to a function to make its curried/not curried behaviour explicit and sticky.

This is going to be more difficult. As explained above, it's not only a matter of compiling the function definition differently (which shouldn't be very complicated) but tracking all the uses of the function: when it's called, how it's called, whether it's wrapped in a closure, composed, etc... Because of the flexibility of F# to compose functions, these scenarios can become quite messy pretty quickly (just check how the [`List.foldBack with composition` test](https://github.com/fsprojects/Fable/blob/master/src/tests/ListTests.fs#L160) is compiled to JS).

Making the interaction with JS as easy as possible is one of the main goals, but the correctness of the generated code has higher priority. Also, I'm not sure the benefits of this would outweigh the costs: instead of remembering to convert the lambda to a delegate (the same pattern as when interacting with C#) you'll have to remember to attach the `[<curried=false>]` attribute to the method definition instead (and this still wouldn't cover anonymous lambdas).


If you're really interested to have an attribute like this we can create a plugin for this so the developer can opt for it at their own risk. I'm not sure if the current plugin hooks allow this, but I can have a quick look.

**Comment by bilkusg** [comment]
I've sent you a pull request with a proposed update to the document.

If adding an attribute is too complicated, then living with the current situation properly documented is probably OK and I realise there are probably more important things to do. For the record, what I most dislike is that the automatic currying on a simple let statement breaks referential transparency - one is normally entitled to assume that 
````
let a = b
````
entitles you to treat a and b as identical. But in this case they aren't. 

If you live entirely within F# then the semantics is unchanged, but as soon as you care about interop with js they are different.

I'm interested in plugins, but they are some way down my list of things to look at - I'm mainly focused on deciding whether to adopt Fable as the basis for some stuff I plan to develop over the next few months, and now I understand it, this issue isn't a show-stopper.

**Comment by alfonsogarciacaro** [comment]
I completely agree with you this should be better documented, thanks a lot for the PR!

And I also agree that the automatic currying is a bit confusing. This comes from the fact that F# is not a pure functional language, so module members are not compiled a function values (=lambdas) but class methods. When compiling to JS the automatic currying looks uncalled for because JS is capable of passing object methods around. However this is not true in all cases, for example with constructors. If the compiler didn't wrap the reference in a lambda the following code wouldn't work:

```fsharp
type Test(i: int)  =
    member val Value = i

[|1; 2; 3|] |> Array.map Test

// Array.from(_fableCore.Seq.map(function (arg00) {
//   return new Test(arg00);
// }, new Int32Array([1, 2, 3])));
```

**Comment by alfonsogarciacaro** [comment]
Docs have been update (I still need to rebuild the website) so I'm closing this issue for now.
