### ISSUE TITLE
Create webpack loader for Fable

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Fable#128]
We could even more easily integrate with current JS stack.

**Comment by alfonsogarciacaro** [comment]
This would be very interesting. I also gave it a thought a few weeks ago and the first difficult I found is that Webpack loaders work file by file while Fable compilation is project based. But I still need to learn more about Webpack loaders, it may be not that difficult to overcome this.

**Comment by fdcastel** [comment]
Just being curious... Could we use [babel-loader](https://github.com/babel/babel-loader) to make something remotely useful here?

Something like:

1. Use Fable to generate AST output
2. Send AST output to babel-loader (*)
3. ???
4. PROFIT!

Please note I don't have the slightest idea what I'm talking about. :sweat_smile: 

(*) A quick glimpse into babel-loader project didn't show up any useful option to use an AST as input. But I assume this would a simple problem to solve. The hardest problems may be the ones Alfonso cited above (project-based vs file-based compilation).

**Comment by alfonsogarciacaro** [comment]
I guess it could be used as a basis but, as you say, it must be modified to make it accept an AST instead of the raw source. In any case, I don't have a deep understanding of how Webpack loaders work so I might be wrong but, as commented other times, I don't see much benefit of using a webpack loader for a full F# project because of the mentioned project-based vs file-base compilation difference. A workflow like the one explained by Krzysztof in his tutorial where Webpack is called in a `postbuild` script should be enough.

A webpack loader may still make sense in a case like #180, where the user just wants to integrate a single F# file in a bigger JS project. In that case the main concern is Fable startup time. For a better experience, Fable must be kept alive and compile source code on demand, that's why I was recommending to use the Suave client which can also be reused for the Try Fable site.

**Comment by alfonsogarciacaro** [comment]
Sorry, if you don't mind I'm gonna close this because there're no plans to create a specific loader for WebPack as there can be problems with the project structure and other workflows (like just calling webpack in the postbuild script) are working fine. Of course, if anybody wants to give it a shot I'll be very happy to provide guidance.

**Comment by 7sharp9** [comment]
Just notices this, I think a webpack loader would be a good idea, I wouldn't be without it for Elm apps.  How would I do a minimal deploy without it?

**Comment by alfonsogarciacaro** [comment]
Fable is compatible with Webpack even without the loader, just run webpack in the `postbuild` script and you're done. There're many examples doing this. Like the ones for Electron ([example](https://github.com/fable-compiler/fable-electron/blob/master/samples/react-todomvc/fableconfig.json#L7))

**Comment by sompylasar** [comment]
FYI https://github.com/mrdziuban/fable-compiler-loader

**Comment by alfonsogarciacaro** [comment]
Hi @sompylasar, thanks for the info, I didn't know about that ;) Please note Fable 1.x is actually integrated with Webpack and there's now an _official_ [fable-loader](https://www.npmjs.com/package/fable-loader).
