### ISSUE TITLE
React sample warnings

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#157]
I've just tried to update the react sample (and my own project) to react 15.1.0 and now the console is being flooded with:

```
warning.js:44 Warning: React.createElement(...): Expected props argument to be a plain object. Properties defined in its prototype chain will be ignored.
```

**Comment by alfonsogarciacaro** [comment]
Wow, React has jumped to v15. Semantic versioning does funny things...

Thanks for reporting this. Hmmm, that's is unfortunate. F# records are a perfect fit for the `props` as they provide static typing and thanks to the way they're compiled by Fable they can have the same effect as a plain JS object (actually, besides the warnings the React sample works normally after updating the `react` package).

I've made some tests and it seems the problem can be fixed in a transparent way to the user by modifying `Fable.Helpers.React` as follows:

```fsharp
let toPlainObj (o: obj) =
    JS.Object.keys(o)
    |> Seq.fold (fun o2 k -> o2?(k) <- o?(k); o2) (obj())

let inline fn (f: 'Props -> #React.ReactElement<obj>) (props: 'Props) (children: React.ReactElement<obj> list): React.ReactElement<obj> =
    unbox(React.createElement(U2.Case1(unbox f), toPlainObj props, unbox(List.toArray children)))

let inline com<'T,'P,'S when 'T :> React.Component<'P,'S>> (props: 'P) (children: React.ReactElement<obj> list): React.ReactElement<obj> =
    unbox(React.createElement(U2.Case1(unbox typeof<'T>), toPlainObj props, unbox(List.toArray children)))
```

The only inconvenience is this adds some overhead at runtime. Another solution could be to add an attribute to make F# records compile as plain JS objects. But I don't like this very much, as it would add subtle semantic differences at runtime.

The third solution would be to compile F# records to plain objects directly in all cases. The biggest inconvenience I can think at the moment for this is the type testing, but this could be solved by attaching the name of the type, as with the interfaces.

What do you think? Do you have any preference or suggestion?

**Comment by alfonsogarciacaro** [comment]
I'd also love to hear @Krzysztof-Cieslak's opinion on this :)

**Comment by davidtme** [comment]
For me having an attribute on the record class would be best as I've hit this problem with other parts of the react eco system, ie. redux.

As these are special classes designed to interact with/be modified by other libraries I don't think you could ever trust that type checking will always work. Could an error message be added if you tried to type check?

**Comment by Krzysztof-Cieslak** [comment]
Modifying `Helpers.React` as suggested above seems OK for me, runtime overhead will be minimal.

**Comment by alfonsogarciacaro** [comment]
Yeah, I've been thinking about this and reached the same conclusion. Making records compile as plain objects may cause some other subtle problems, and having the attribute won't be very safe either, as the programmer is forced to remember to attach it, and it won't be until runtime (and through the browser console) that they'll notice if they forget.

I'll edit the React Helper then. Thank you both for your help! :+1:
