### ISSUE TITLE
Typed arrays and other type-directed representation choices

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fable#169]
This is a question/discussion based on a conversation with Tomas Petricek

My understanding is that Fable uses typed arrays for some instantiations of arrays, e.g. ``int32[]``. However, in general typed arrays will _not_ be produced by generic code that produces a ``T[]``  (when T is int32).  The resulting ``int32[]`` may be passed on to code that might otherwise expect a typed array.

Tomas says that some special cases like ``Array.map`` are handled by inlining, but in general generic code will produce an array, not a typed array.  

So my basic question is - is the use of typed arrays by Fable sound when faced with libraries of generic code?  For example, are typed arrays consumed in a way that assumes they are typed arrays?  Or will all consumption points also work if the array is either a typed array or a normal JS array?

In general using type-directed representation choices (i.e. where representations are dependent on a generic parameter) needs care - I just wanted to check that Fable is being implemented with this in mind.  I know that the compilation of Fable for "option" types is not fully sound (though I think there should be an option to make it sound :) ), but I just wanted to check this wasn't a problem with arrays too.

(If it turns out this is a problem, you can, if necessary, introduce a new type of ``FastArray<_>`` that compiles efficiently, and which is always inlined, and with conversions to/from normal JS arrays)

**Comment by alfonsogarciacaro** [comment]
Thanks for the question, Don! Most of your assumptions are right. It's true that typed arrays are not fully sound when calling generic functions in a generic library. However, from the beginning compilation to typed arrays was thought as an "extra" for performance and no consumption point assumes that the array is actually a typed array. In the few cases were typed and non-typed array methods differ in JS, the core lib takes care of checking the object (e.g. [setSlice](https://github.com/fsprojects/Fable/blob/master/import/core/fable-core.js#L718)).

When calling a function from the core lib, Fable makes the conversion to a typed array if necessary (see [here](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Replacements/Replacements.fs#L925) for example) though, as commented above, this is not done for custom-defined generic code. We could add a check to custom generic code too, it shouldn't be that difficult. 

In FunScript, generics was one of the biggest issues. FunScript generated concrete implementations of generic functions as needed in order to keep the full semantics (reflection was even possible). But this increased a lot the size of the final JS and made it very difficult to create libraries callable from JS.

About options, one of Fable's guidelines is that it's possible to sacrifice a bit F# semantics to generate more idiomatic code and make interaction with JS easier (I understand this is very arguable). For example, Typescript interface optional members are translated as properties with an option type. This works because type testing translates to `== null` which is also way to check if a property exists in JS. If we introduce a compiler argument to generate real options this trick (and likely others) won't work anymore.

**Comment by alfonsogarciacaro** [comment]
Closing this for now, please reopen it if you think the current situation with typed arrays can/must still be improved :)
