### ISSUE TITLE
Integer division results in floats

### ISSUE THREAD

**Issue by jsayres** [fsprojects/Fable#172]
`123456 / 10` will result in 12345.6, which is unexpected when working with ints.

Worse, if I make an explicit function:

`let div (x : int) (y : int) : int = x / y`

This compiles, when it really shouldn't, since the javascript division will result in a float.

**Comment by alfonsogarciacaro** [comment]
This is tricky and we already had a similar discussion in the past (#74). I know integer division is one of the most common examples but if we want to keep the full semantics for primitive values we'll have to solve also many other issues (overflows for `byte` and `short`, compile `char` as a number, etc...) which would force us to have a "runtime" to coerce the results of any arithmetic operation, something Fable tries to avoid by design.

In the docs is stated that all [numeric primitives compile to JS Number](http://fsprojects.github.io/Fable/docs/compatibility.html#Primitives) so the programmer should be aware of these potential issues when compiling to JS.

How important is this for your app? We could open a discussion to ask users if they want to a type checker wrapping all divisions. In the last case, a plugin can be created for the specific needs of a user, as it was done with the [byte arithmetics](https://github.com/fsprojects/Fable/blob/master/src/plugins/Fable.Plugins.BitwiseWrap.fsx).

**Comment by jsayres** [comment]
Thanks for the info, and I can see the difficulty you're having.

I'm not sure what the answer should be. But I think at the very least, the compiler should catch the sample I had above and give me some way of knowing that the type expectations I have won't be realized.

Just brainstorming, but since it seems that you're not really implementing CLR number types, would it make sense to simply introduce a Number type and encourage people to use that rather than ints and floats?

Sorry if this is all ridiculously naive. I'm relatively new to F#, and very new to Fable. But I love it so far!

**Comment by fdcastel** [comment]
I see your point, @jsayres, and I already had the exactly same thoughts when I was starting with Fable (I'm the original poster of #74, BTW :) )

However, as we discussed in #74, the overhead to make this change would be immense. And it would benefit only some very specific use cases, to the detriment of general usage.

To put it simply: It's just not the Fable objective to keep the full F# semantics when generating the JS code. I understand it could be a surprise for new users (which didn't read the docs :wink: ), but a compiler warning in this case would be a no-go, since this is the expected behavior.

In my particular scenario, I solved the problem (to keep byte arithmetic working) with a [plugin](https://github.com/fsprojects/Fable/blob/master/src/plugins/Fable.Plugins.BitwiseWrap.fsx). This way, I can get my (very peculiar) code working without annoying other Fable users ;)

What do you think? Would this work for you? If you need some help please make a Gist with some expected use cases from your code and I will be glad to help you.

**Comment by jsayres** [comment]
Thanks for the feedback, @fdcastel. I'm going to push back a bit, but I sincerely appreciate it. :)

I actually did read the docs, but the behavior was still surprising to me. To be clear, I'm not suggesting that Fable actually implement all the CLR F# `int` semantics in the compiled javascript. Rather, I would simply expect the compiler to let me know what's supported and what's not. You stated that a even a compiler warning in the example I provided would be a no-go. Can you explain why? If the division does not in fact return an `int`, aren't my type expectations wrong in that case? If the compiler lets that through, doesn't it introduce a very subtle bug in my program?

Consider how purescript handles this same situation: [https://github.com/purescript/purescript/wiki/Differences-from-Haskell](https://github.com/purescript/purescript/wiki/Differences-from-Haskell) (See the Numbers section.) It uses `Int` where it makes sense and supports it to a reasonable degree, but then it uses a `Number` type otherwise to match javascript expectations. If the goal of Fable is to be a "javascript F#", and not a "CLR F#-to-javascript", wouldn't that make sense?

As I mentioned in my previous comment, maybe this viewpoint is uninformed and naive, which is entirely possible! Nevertheless, I just can't see how allowing `let div (x : int) (y : int) : int = x / y ` to compile is a good idea, and I think it will ultimately inhibit adoption by front-end devs looking for a type-safe functional language to replace the "everything goes" javascript they're currently stuck with.

**Comment by alfonsogarciacaro** [comment]
Thanks for the insightful discussion. I just introduced the warning system recently (though it doesn't emit any warning quite yet) so a warning could be a good compromise for this case. I think @fdcastel didn't know that yet, that's why the said it'd be a no-go :)

PureScript is a great example to show the frictions in the difficult balance Fable tries to keep: it doesn't want to create a new language (like PureScript, Dart, Elm, TypeScript...) but at the same time it wants to be as close as possible to JS. I think the best selling point of F# is the compiler and editor tools and trying to force a non-CLR numeric type, while possible, will make programming much less pleasant (e.g., the F# compiler automatically infers `let f x y = x + y` to be of type `int` and this cannot be easily prevented).

So, if you agree, I'll just add a compiler warning when you try to divide integer types. However, I don't know if it's because it's still early in the morning but right now I'm thinking that wrapping integer divisions with `Math.floor` may not be a bad idea after all :) So if you want to push for the wrapping, this is your opportunity... until it becomes late in the evening, I get tired and I start rejecting changes again ;)

**Comment by jsayres** [comment]
Sorry for the delayed reply.

Your explanation makes things clearer, thanks! I can see how working with type inference makes things problematic.

A warning might be enough for now, as long as you don't think it would be a major annoyance to existing users. Same with actually truncating the result for an integer division. It would work great for me, since that would be what I would expect, but I don't want to cause issues for others. You would understand the ramifications of such a change far better than me.

Again, thanks to you and @fdcastel for helping me understand the issue better. Whatever you decide to do in the end, I should be able to work with it.

**Comment by alfonsogarciacaro** [comment]
I just woke up and I recently found out about the [~~ trick to floor JS numbers](https://coderwall.com/p/9b6ksa/is-faster-than-math-floor) so at the end I'm wrapping all integer divisions 😸  Please update to v0.3.14 to get change.

Thanks a lot for pointing this out and being so understanding with my (sometimes seemingly capricious) changes of opinion!
