### ISSUE TITLE
Support passing code from stdin.

### ISSUE THREAD

**Issue by irium** [fsprojects/Fable#180]
To implement Fable webpack loader the Fable should allow receiving some `F#` code from stdin and output `js` back to stdout. Thus, implementing webpack loader on top of it would be just a few lines of code.

**Comment by alfonsogarciacaro** [comment]
Very happy to know you've been checking how to make the Webpack loader! This should be possible and I'm actually planning to do something similar to bring back the online REPL. But... (and this is a big but) this would only work if the F# code corresponds to a `.fsx` script. If it belongs to a file in a project, this will be much more difficult because in order to parse the code you need to [read the project options from the `.fsproj` file](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Main.fs#L90).

I haven't checked Webpack loaders very deeply so I may be terribly wrong, but I had the impression they load the code file by file. Do you think it would be possible to pass the F# project instead? If it isn't we can still build the loader, even if it only works for script (we'll also have to check what do if that script has references to other files).

**Comment by alfonsogarciacaro** [comment]
Related to #128

**Comment by irium** [comment]
> this would only work if the F# code corresponds to a .fsx script

Surely. This is exact scenario I'm interested in. Essentialy Webpack loader is function that receives source code string and returns somehow processed code string.

Mention: not a file name, but file content already. So we **don't** know the file name :(
As for references to other files: we could replace them with JS `import` or `require` depending of `module` setting.

P.S.
I want to port just _some_ JS files to `Fable` in existing JS SPA project. The main reason that stops from porting the whole app - lack of `jsx` support which I suppose isn't near-time goal.

**Comment by alfonsogarciacaro** [comment]
Ok, I'll work on that. I think the use cases will be limited as it'll be only possible for scripts as we mentioned and references may not work properly (it's a bit more complicated than just replacing them with `import`), but I have to do it anyway for the online REPL anyway so the work can be reused.

Another concern is you need to keep the Fable process alive or compilation/loading will take too long every time (there's usually a 5 secs warmup). But this can be solved with the Suave server that's also planned for the REPL.

About JSX, we're not planning to support it. I'm reluctant to support any syntax different from F#. First because I don't know how to do it ;) and second because we want to take full advantage of the current editor support for F#. However, we *do* have a DSL for React components which IMHO is better than JSX, or at least more idiomatic in F#. You can check how to use it in the [React sample](https://github.com/fsprojects/Fable/blob/master/samples/browser/react/src/client/components.fs#L65-L75). Also see [this issue](https://github.com/fsprojects/Fable/issues/70) for more info on how the React helper was designed.

Besides that, the React sample also shows how to use Webpack and Fable watch compilation in your workflow. You can also check [Fable Introductory Video](https://www.youtube.com/watch?v=iP-50fj06Eo) from min 6:30. If this workflow is good for you, you may don't even need the Webpack loader.

**Comment by alfonsogarciacaro** [comment]
Merge with #177

**Comment by irium** [comment]
> About JSX, we're not planning to support it.
Don't worry. As I've mentioned - there's no urgent need. Source text compilation, especially together with live process running - should be enough to make me (and Webpack) happy :) 

I hope I'll somehow get to get it working. As for JSX - I could write a community-side project (a-la plugin) for preprocessing that, but as you've mentioned - this is not enough because it requires editor support - which is much more complicated task.

I've seen all examples, and not happy with React DSL because I'm not hardcore F# developer :)
Most complexity in my project is in the model - so I began to look for some functional client-side language. Initially it was ELM (and it's really cool language for writing SPA logic), but they don't support "per file" compilation and never will do :( Another drawback - difficult integration with outside JS world.
So my eyes fell on Fable :)

I'm fine with keeping separate UI in JS-React and having model logic in F#-Fable as long as we will get Webpack loader working.

**Comment by alfonsogarciacaro** [comment]
Still a WIP but I've uploaded a Suave client to `fable-clients`. If you want to give it a try, you can test it with the following commands:

```
./build.sh FableSuave
mono build/fable/Fable.Client.Suave.exe
```

Then you can send an HTTP POST to `http://0.0.0.0:8083/fable/` with the code you want to compile. You can use `Fable.Core.dll` but any other reference won't work. Also you won't receive the JS code directly but a Babel-compatible AST that must be transformed as you can see [here](#r "../import/core/Fable.Core.dll").

Please tell me if you have any questions. Have fun!
