### ISSUE TITLE
Properties Case

### ISSUE THREAD

**Issue by danfma** [fsprojects/Fable#216]
### Description

By default, properties in Javascript are camel case but if you use some editor or write real code in F# you probably will want to write using the specification of the language, which dicts that you should specifiy properties at pascal case.

It would be nice if the compiler can convert the property names from pascal case do camel case at compile time. That could be done in a per project configuration at the fableconfig.json. The `Bridge.NET` project also do something like this, when converting from C# to JS.

I'm being purist here, but I don't think that we should mix specifications. I can not force the .NET libraries to use camel case, neither javascript libraries to use pascal case. With a little help from the compiler, we could retain the language definitions and patterns from each environment at maximum as possible.

**Ok, now I see that only when interoping with the .NET libraries is when F# uses pascal case, but that could be a nice feature anyway.**

**Comment by alfonsogarciacaro** [comment]
Hi @danfma and thanks for expressing your opinion!

We can open a discussion but I wouldn't be very inclined to this. Actually, this is already done with the [JS library](https://github.com/fsprojects/Fable/blob/master/import/core/fable-core.js) where all the member names and in camel case and for some common interfaces like `IObservable` or `IComparable`. However doing this for types defined by the user can be problematic. One of the guidelines of Fable is to produce as standard JS code as possible, and for this purpose it already makes some operations behind the curtains. Unfortunately this forces the user to know Fable's internals in order to understand some special interoperability situations. Arbitrarily changing the case of member names would increase this cognitive load without adding too much value.

As an example of potential conflicts this could cause, we already had to [change union type members to upper case](https://github.com/fsprojects/Fable/pull/100) so JSON serialised objects could be read with Json.NET on the server side.

**Comment by danfma** [comment]
Hi @alfonsogarciacaro! Thanks for the answer too!

I agree with you and I understand the problematic points too.

**Comment by alfonsogarciacaro** [comment]
Perfect, thanks for your understanding. I'll be closing the issue for now, but please feel free to reopen it if you think it should be reconsidered. Cheers!
