### ISSUE TITLE
Recursive values give "no enclosing entity" error

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#237]
Fable 0.3.26 fails to translate the following:

```fsharp
module Foo

let delay (f:unit -> unit) = f

let rec a = delay (fun () -> b())
and b = delay a
```

You get an error:

> the value or member doesn't have an enclosing entity

The workaround is not to use recursive value definitions (recursive functions work just fine).

**Comment by tpetricek** [comment]
(This is not very urgent issue, but I wanted to log it with a small repro as I just encountered it with more fancy example :-))

**Comment by alfonsogarciacaro** [comment]
Not urgent issues nicely reported with code to reproduce the problem is what I like 😉 Well, I like it even more when they also come with a PR 😄 but it's ok, this shouldn't be very difficult: recursive bindings are a bit tricky and so far I didn't pay too much attention to them. I'll have a look, thanks for the report!

**Comment by alfonsogarciacaro** [comment]
Wow, I had a look at this and it's really complicated to fix as the F# does a lot of magic with recursive values. Taking about values... Do you think there's much value at adding this feature to Fable? We could just detect the warning 40 and throw a message saying that recursive value definitions are not supported in Fable (together with the location of the problem).

**Comment by alfonsogarciacaro** [comment]
As the fix is complicated and I'm not sure many people will use recursive value definitions, for now I'm just [disallowing it with a proper error message](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Client.Node/Main.fs#L111). I hope that's ok. If not, please feel free to reopen the issue and we can try to tackle it down later.

**Comment by tpetricek** [comment]
That sounds pretty reasonable :) recursive values are weird
