### ISSUE TITLE
Decimal literals don't compile

### ISSUE THREAD

**Issue by tastyeggs** [fsprojects/Fable#239]
Sample script:

`let x = 1.0m`
`printfn "%A" x`

Produces the following output:
Cannot find replacement for Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.makeDecimal (L1,8-L1,12)

Guessing [this](https://msdn.microsoft.com/visualfsharpdocs/conceptual/intrinsicfunctions.makedecimal-function-%5bfsharp%5d) function needs to be implemented.

**Comment by alfonsogarciacaro** [comment]
Hi there and thanks for the report! It's a bit more complicated than that, because decimals are a type of its own (with several numerical components) and all the arithmetic operations must be implemented in order to translate it to JS with the full semantics.

This is related to #205 were support for BigInteger was requested and it was discussed how to implement it (adding the type to `fable-core` or using an existing JS library). In any case, implementing decimals and big integers would be nice but requires some work and it has low priority at the moment. Of course, if you want to give it a try at implementing I'll give you as much support as I can.

Cheers!

**Comment by alfonsogarciacaro** [comment]
I wouldn't do it in the standard library but if for some reason you're happy to use JS numbers for decimals, it could be easier to write a plugin to just do that.

**Comment by tastyeggs** [comment]
Got it, I figured as much. I don't really need decimals right now, but I was working on sharing some domain models between my backend and frontend and hit upon this issue. Yes, plugin seems the way to go.

Thanks.
