### ISSUE TITLE
Suggestion - use local Node and npm installations

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Fable#26]
Both Node.js and npm can be locally installed from NuGet (using Paket). This will make build totally reproducible - it won't require users to have any additional software installed.

Same things is done for FsSnippet project -  https://github.com/fssnippets/fssnip-website

**Comment by alfonsogarciacaro** [comment]
Mmm, node is so easy to get and so extended nowadays I don't think it'll be a hurdle for users to install it. Furthermore my actual idea is to distribute Fable through npm instead of NuGet. I'm also planning to include integration with other JS development tools (like Webpack) that may conflict if node is not globally installed. Closing the issue for now, but we may reconsider this if it affects other developers.
