### ISSUE TITLE
Unexpected DecisionTree branch

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#306]
The following code snippet fails to compile:

```fsharp
let (|A|) n = n

let kill = function
  | Some(A n, Some(A m)) -> n + m
  | _ -> 0
```

The error I get is the following:

```
ERROR: Unexpected DecisionTree branch in (L160,11-L160,19): Let
  ((val activePatternResult18297,
    Call
  (null,val |A|,[],[type Microsoft.FSharp.Core.int],
   [UnionCaseGet
  (TupleGet
  (type Microsoft.FSharp.Core.int * Microsoft.FSharp.Core.int Microsoft.FSharp.Core.option,
   1,
   UnionCaseGet
  (Value val _arg1,
   type Microsoft.FSharp.Core.Option<Microsoft.FSharp.Core.int * Microsoft.FSharp.Core.int Microsoft.FSharp.Core.option>,
   Some,field Value)),
   type Microsoft.FSharp.Core.Option<Microsoft.FSharp.Core.int>,Some,field Value)])),
   DecisionTreeSuccess
  (0,[Value val activePatternResult18297; Value val activePatternResult18296])) 
```

It does not happen when I use the active pattern just once - and it is easy to avoid this with a workaround, so not a blocking issue...

**Comment by alfonsogarciacaro** [comment]
Pattern matching representation is a bit complicated in FCS AST (it is simpler in the quotations where they just become nested `IfThenElse`) and TBH I'm really amazed [the code to identify and optimise (a bit) them]() has been working fine with almost no changes since the first version :wink:

I'll have a look, hopefully this is fixable. Actually we should have more tests with pattern matching just in case.

**Comment by alfonsogarciacaro** [comment]
Well, at the end it was not that difficult to fix. We've been lucky the patch worked on the first try because I hardly understand that part of the code anymore 😅
