### ISSUE TITLE
Show the javascript output of the compiler

### ISSUE THREAD

**Issue by urbanhop** [fsprojects/Fable#307]
Would find it very helpful if there would be examples of the compiler's output, so we can see emitted javascript files without the need to install the compiler. Unfortunately even the samples seem to hide the output, as it is already minified.

Maybe you can check in the javascript output to the samples? Or make it available on the samples web page .

anyway, thx for your work.

**Comment by alfonsogarciacaro** [comment]
Hehe, so you don't take the "JavaScript you can be proud of" slogan for granted :wink: In general, I prefer to gitignore automatically generated files to prevent pollution of git history. Probably a better solution would be to add an online REPL to the web so the compiler can be tested directly on the browser. This is already planned (see #177) but I haven't had the time yet to finish it as other features  had priority.

In any case, the JS code of the samples in the web is not minified. Because of the source maps, the browser debugger probably will show you the F# source first, but you should still be able to check the JS code. For example in the Mario sample page, with Chrome debugger you should find the JS code in the _Sources_ tab: `fsprojects.github.io/Fable/samples/mario/mario.js`.

**Comment by urbanhop** [comment]
thx, you are right the files are not minified, reading them suffices my purpose. an online repl, (try-fable , #177) would certainly be perfect.

the js is nicely readable, which is not so often the case with lang-to-lang compilers - great. the translation of curried functions is nice to read, from a performance point of view it could be improved:

    var f = function (x) { 
       return function (y) { 
          return function (z) { 
               return function (u) { 
                    return function (v) { return x+y+z+u+v }
                }
              }
           }
        }
    f(1)(2)(3)(4)(5)

is *much* slower than 

    f(x,y,z,u,v) { return x+y+z+u+v; }

(cant send a jsperf as its down)

the compiler could find all callings of functions and make js output more efficient. on the other hand, the coder could simply use tuple arguments for functions where performance matters, restricting function currying only where it is utilized. so that sounds solvable.

**Comment by alfonsogarciacaro** [comment]
You're right. This has already been discussed (see #125) and actually I tried to do the same in the early stages of Fable (indeed this is already done for calls to `fable-core` functions: Seq, List, Array...). Unfortunately, this becomes unmanageable in complex composition scenarios. For performance and for easier interaction with JS you can always use delegates (like the [d3 sample](https://github.com/fsprojects/Fable/blob/master/samples/browser/d3map/d3map.fsx#L51-L62) does). More info in the [docs](http://fsprojects.github.io/Fable/docs/interacting.html#Calling-F-code-from-JavaScript) (note F# function with tuple arguments are not the same as delegates).

**Comment by urbanhop** [comment]
ahh, i see, very helpful, thank you!
¡que tengas un buen día!
