### ISSUE TITLE
Fable React cannot specify SVG height

### ISSUE THREAD

**Issue by chrisdavies** [fsprojects/Fable#316]
### Description

I'm trying to use Fable + React to generate an SVG. I'm trying to create an SVG element that looks something like this:

    <svg width="2000" height="2000" ...

The problem is that the `height` attribute is defined by Fable as a CSS property, and so it cannot legally be applied to the SVG element.

Here is some sample code that reproduces the issue:

    let svg children =
      R.svg [
        R.Props.HTMLAttr.Width 2000.0
        R.Props.Height 2000.0
      ] children

### Expected behavior

I expect to be able to legally define Height for an SVG.

### Actual behavior

The type system is not set up to allow Height to be a legal attribute of SVG.

### Known workarounds

Please provide a description of any known workarounds.

I suspect I could use `R.Props.DOMAttr.DangerouslySetInnerHTML` to generate the SVG, but I'd lose all type safety, and may as well not use Fable at that point!

**Comment by alfonsogarciacaro** [comment]
The height property is [actually there](https://github.com/fsprojects/Fable/blob/master/import/react/Fable.Helpers.React.fs#L418), I just commented it out because another user said it was conflicting with CSSProp.Height and wasn't useful for HTML5 (though, as you point out, it is for SVG). Something similar happens to the `Color` property.

I'll try to think of a good solution. For now, as the React helpers is just a file you include in your project, I guess the easiest solution is that you remove the comment so you can use the property. Also remember that is possible to use directly a tuple (like `("height", 2000)`) with KeyValue lists for cases like this. Check [the docs](http://fsprojects.github.io/Fable/docs/interacting.html#KeyValueList-attribute).

I hope this helps!

**Comment by chrisdavies** [comment]
Woah. Yeah. I didn't know about that tuple solution. That works just fine for me!
