### ISSUE TITLE
Error when running "build MochaTest" on Windows

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#318]
I'm still getting one error when building Fable - I've seen this before, but I'm not sure what could be causing this. My build might not be entirely clean because `build Clean` fails on Windows (paths too long), so I deleted old build folders by hand - but I may have forgotten some...

The error I'm getting is:

    cmd /C npm run test --

    > fable-tests@0.1.0 test c:\tomas\public\fsprojects\Fable\build\tests
    > mocha .

    module.js:327
        throw err;
        ^

    Error: Cannot find module './DllRef/DllRef/Util/Util'
      at Function.Module._resolveFilename (module.js:325:15)
      at Function.Module._load (module.js:276:25)
      at Module.require (module.js:353:17)
      at require (internal/module.js:12:17)
      at Object.<anonymous> (c:\tomas\public\fsprojects\Fable\build\tests\MiscTests.js:15:14)

**Comment by alfonsogarciacaro** [comment]
Isn't the DllRef project being correctly built here? https://github.com/fsprojects/Fable/blob/master/build.fsx#L226-L227

**Comment by tpetricek** [comment]
I'll investigate...

**Comment by tpetricek** [comment]
So, it looks like the relative path in `build/tests/MiscTests.js` is incorrect when I run the build. The generated file contains the following:

    var _Util5 = require("./DllRef/DllRef/Util/Util");
    var _Lib = require("./DllRef/DllRef/Lib");

When I change this to the following, it runs fine:

    var _Util5 = require("./DllRef/Util/Util");
    var _Lib = require("./DllRef/Lib");

**Comment by tpetricek** [comment]
Humph... I just got the error in another project changing the name of the folder where I have the project.

Previously, the path was `C:\Tomas\Public\thegamma\experiments` and it was correctly generating requires such as:

    require("thegamma/providers")

I moved the project to `C:\Tomas\Public\thegamma\thegamma-experiments` and then it started generating wrong requires:

    require("thegamma/thegamma/providers")

It seems that the path is somehow incorrectly generated depending on the directory where your project is. I'm not sure how this would be related to the `DllRef` error because I do _not_ have Fable in a directory including `DllRef` in the name :)

**Comment by alfonsogarciacaro** [comment]
Now this is weird, the build is working fine in AppVeyor and also when I test it in Windows 10. Are you using Windows 7/8? Some mysterious bugs have been reported for these systems, but it's difficult for me to fix because I can't reproduce :/

Also, this didn't happen to you before, did it? Since when did it start happening? The structure of the tests projects hasn't changed in a while.

[This is the part](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Compiler/Fable2Babel.fs#L145-L149) that creates the relative paths from one file to another file in a referenced project. Could you please try using it in FSI to see if you the expected results? ([These are](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Core/Util.fs#L152-L173) the called functions.)

Another possible cause is that, when referencing a dll I don't have a "project file" so I have to use another strategy to calculate the base directory for the rest of the files. Maybe there is a problem with [this line](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Compiler/FSharp2Fable.fs#L956)?

**Comment by alfonsogarciacaro** [comment]
Just in case, I posted [here](https://gist.github.com/alfonsogarciacaro/17b94bb217af6d1a62286b5e91975595) the configuration I use to debug Fable with Visual Studio Code. If you want to give it a try, put the `launch.json` file in `.vscode` dir and add a break point [here](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Compiler/Fable2Babel.fs#L147). Probably you also want to remove everything in `Fable.Tests.fsproj` but `MiscTests.fs` to speed up compilation.
