### ISSUE TITLE
Add type validation when deserialising json

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/Fable#332]
It's could be good to have type validation when deserialising the json file. 

Like so we could help the user track bug and garantee the data getted from the server.

**Comment by theprash** [comment]
To clarify, the target type in the type parameter from `JsInterop.ofJson<T>` should be passed into the TypeScript [`ofJson` function](https://github.com/fsprojects/Fable/blob/87891e955454e4eb3e282674d6a45a265cd1473d/src/fable/Fable.Core/npm/fable-core.ts#L255) so that it can it can enforce that the JSON matches the target type.

It could throw an exception if the types do not match, but maybe it would be better return an Option or Result type to get more compile time safety. Bear in mind that F# 4.1 will have a [Result type](https://github.com/fsharp/fsharp/blob/1722f2ecd3fd6e4660cd27d52ac9b180e5c51851/src/fsharp/FSharp.Core/prim-types.fsi#L1775).

**Comment by theprash** [comment]
After this change it may be possible to omit the `$type` JSON key from built in F# data structures like `List` and make the serialized JSON smaller.

**Comment by alfonsogarciacaro** [comment]
Unfortunately the problem with `List` is not so much deserialising directly a list (which could be resolved by the change proposed here) but having a list nested in another type. For example, with a JSON like: `{ "myName": "A", "myList": [1,2,3] }`, Fable cannot know `myList` must be deserialised as a list (arrays are serialised as normal JS arrays so you can use them if you want to have lighter JSONs).

**Comment by alfonsogarciacaro** [comment]
About `ofJson` returning an option, I'd like to keep breaking changes to a minimum from now on. We could add an additional `tryOfJson` though.
