### ISSUE TITLE
typescript2fable Inheritance 

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#44]
I have an idea on how to get around inheritance problems especially an interface extending a class:

I've got some work in progress but before I finish I'll like some feedback

```
// interface FirstInterface {
//      FirstFunction(s: string): void
// }

// Would generate the following code:

// An interface prefixed with I
type IFirstInterface =
    abstract FirstFunction : string -> unit

// An abstract class which implements the interface
// This means any child class can inherit this class and not worry about implementing interfaces
[<AbstractClass>]
type FirstInterface =
    interface IFirstInterface with
        member x.FirstFunction(s): unit = failwith "Not implemented yet"

// class SecondClass implements FirstInterface {
//      SecondFunction(i: number): void
// }

// Would generate the following code:

// The interface in needed so any child interfaces can use this.
type ISecondInterface =
    inherit IFirstInterface
    abstract SecondFunction: int -> unit

// Same as the interface generated code but not an abstract class.
type SecondInterface =
    inherit FirstInterface
    interface ISecondInterface with
        member x.SecondFunction(i: int): unit = failwith "Not implemented yet"


// interface ThirdInterface extends SecondInterface {
//      ThirdFunction(b: bool): void
// }

// This interface can now inherit without any problems

type IThirdInterface =
    inherit ISecondInterface
    abstract ThirdFunction: bool -> unit

[<AbstractClass>]
type ThirdInterface =
    inherit SecondInterface
    interface IThirdInterface with
        member x.ThirdFunction(arg1: bool): unit = failwith "Not implemented yet"
```

**Comment by alfonsogarciacaro** [comment]
Looks like a great idea! If you send a PR I'll test it. It'd be better if we can restrict this solution when the interface is being inherited (few cases) to avoid too much boilerplate, but I think I can do that. We may still have to fake some constructors, for example, `FirstInterface` abstract class needs a constructor so `SecondInterface` can inherit from it.

**Comment by alfonsogarciacaro** [comment]
This has been fixed a bit differently, see [explanation](https://github.com/fsprojects/Fable/pull/48#issuecomment-190884373).

**Comment by davidtme** [comment]
@alfonsogarciacaro I've found a new problem which this pr could help with solving... optional interface members

To create class in react it i should be able to do this:

```
type CC() =
    interface React.ComponentSpec<obj, obj> with
        member x.render(): ReactElement<obj> = 
            // Some code here
        member x.displayName
            with get (): string option = 
               // Some code here
            and set (v: string option): unit = 
               // Some code here


let spec = new CC()
let cc = React.Globals.createClass spec
```

but because React.ComponentSpec (and what it extends) I'm forced to implement all 16 optional members, which normally react would take care of.

Could the new parser detected optional members and create an abstract class etc?

**Comment by alfonsogarciacaro** [comment]
You're right, that'd be a good case to create the abstract so you're not forced to implement all methods. Right now the dirty solution would be not to implement the interface and cast with `unbox` later, but then you lose the compiler static check.

BTW, checking the `React.ComponentSpec` interface I also noticed I still need to implement indexers.

**Comment by alfonsogarciacaro** [comment]
This is proving to be challenging: I explored your suggestion and translated the optional methods as [abstract methods with a default implementation](https://github.com/fsprojects/Fable/commit/74b4f145dc6282e69e8ac5628b8ab1e9c27dc27c). However, when I tried to implement `React.ComponentSpec` it didn't work, as `React.createClass` expects a plain object and not a class instance (it doesn't look for `render` in the prototype). Then I [extended React.component](https://github.com/fsprojects/Fable/blob/react/sample/browser/react/app.fsx#L28-L31) as explained in the [docs](https://facebook.github.io/react/docs/reusable-components.html#es6-classes) and this time worked :) This is interesting because you can use typed `props` using generics.

I had to do so many changes that I pushed them to a different branch for the moment. I'll merge them with `master` shortly. But I think I'll leave out the part about the optional methods because it complicates the parser and it's not adding much value (it also make confuse users because in most cases dummy abstract classes won't have actual default implementations). It's complicated to try to get too close to React quirks, and I'd prefer not to have to tweak the compiler & parser too much in order to fit a specific framework (though it's true that thanks to the tests and your suggestions I've managed to fixed other issues). Maybe the best approach is to create a middle layer (I'm trying to do [something similar with Vue](https://github.com/fsprojects/Fable/blob/master/sample/browser/todomvc2/app.fsx#L29-L46)) so it's possible to interact with the library using a more F# idiomatic DSL, something similar to what ClojureScript does with Om and React.
