### ISSUE TITLE
Feature request - Object expression from classes are not supported

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#63]
Just wondered if there is a technical reason why *Object expression from classes are not supported* such as:

```
let obj1 = { new SomeClass() with member x.ToString() = "" }
```

or is it a something todo?

**Comment by alfonsogarciacaro** [comment]
I tend to think that everybody has my coding preferences and didn't deem this as important ;) The problem is that it would be easy to create a plain JS object on the fly (like your approach suggests in the PR) but unfortunately this would break the reflection system I'm trying to maintain.

Right now records, union types, classes are implemented with ES6 classes so it's possible to type test them at runtime (for interfaces, I'm attaching a Symbol property with the names). However, to make it possible in your example to test that `obj1` belongs to `SomeClass` inheritance chain, it would be necessary to instantiate `SomeClass` and then monkey patch its member which is a bit cumbersome and I haven't figured out yet an elegant way to do it.

If we introduce an exception and leave it as a plain object this may cause an expectation problem later at runtime which is probably worse than a compilation fail.

It's not possible for you to work around this? What are you trying to achieve actually?

**Comment by davidtme** [comment]
At the moment I’m mocking up/test different parts of a bigger application. I came across this trying to mock up server side react-router

https://gist.github.com/davidtme/6b03dcb3bbc17f3eb75f#file-program-fs
*(This is using a custom ts2fable which creates abstract class)*

I wanted to try to emulate the style in [React Router Route Configuration](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md) - Configuration with Plain Routes.

https://github.com/fsprojects/Fable/pull/64 gets this working to a point - it blow with:

```
var arg10 = tupledArg[0];
TypeError: Cannot read property '0' of null
```
but that's a different issues

**Comment by alfonsogarciacaro** [comment]
JS allows class expressions so maybe it's possible to create a class on the fly. However, I'm still troubled about generating abstract classes when parsing TypeScript definition files, because Fable will expect this class to have a constructor and if it doesn't exist an error will be thrown at runtime. To create components with static type checking I'd recommend to use the new React helper (soon to be included in the `fable-import-react` npm package) [as it's done in the React sample](https://github.com/fsprojects/Fable/blob/master/samples/browser/react/public/components.fs#L174).

**Comment by davidtme** [comment]
the abstract TypeScript definition files aside (I'm not going to try and push that) could you give me some F# code that would be problematic and I'll try to come up with a safety net

**Comment by alfonsogarciacaro** [comment]
If you do something like this:

```fsharp
type SomeClass() =
    class end

let test() =
    let obj1 = { new SomeClass() with member x.ToString() = "" }
    match box obj1 with
    | :? SomeClass -> true
    | _ -> false
```

The result of `test()` must be `true` as type testing is supported by Fable. However, by creating a simple JS object with the members of `SomeClass` attached this won't be possible because the type test will check whether `obj1` belongs to `SomeClass` prototypal inheritance chain. 

I think it would be possible to keep the inheritance chain by generating something like the following (weird but valid) ES6 code:

```js
class A {
	constructor() {
	}
	toString() {
		return "A";
	}
}

var obj1 = new (class extends A {
	constructor() {
		super()
	}
	toString() {
		return "Object expression"
	}
})();

console.log(obj1 instanceof A);
```

It shouldn't be very difficult and I'm planning to do it when I have time, but if you want to give it a shot I'd be very happy to review your PR :)

**Comment by davidtme** [comment]
Thanks @alfonsogarciacaro for the sample, I'll have a go - If you get this done before me it's no great loss as it will give me a change to learn how Fable (your ace coding) and babel ast works :)
