### ISSUE TITLE
exports.default.xxx

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#67]
I'm trying to get react hot reloading working and I've encounter a bit of a problem. When the hot loader searches for react components it looks in ```exports.xxx``` and everything that Fable produces goes in ```exports.default.xxx``` so the hot reload can’t find it.
Would it be posable to not put everything in default (or copied to export.)? I think this would also have the advantage of playing well with other JS applications such as able to use the es6 import statement
```
import { member } from "module-name";
```

*(Sorry if this is completely wrong es6 import/exports still confuse me)*

**Comment by alfonsogarciacaro** [comment]
Yeah, I faced the same problem and thought the same thing. Unfortunately it's not possible (or very difficult) to export using ES6 namespaces because they don't accept string literals as names for the values and functions which would complicate the naming rules in Fable and the use of custom operators.

The good news is that it's possible to fix the react-hot-loader itself. I submitted a [PR](https://github.com/gaearon/react-hot-loader/pull/236) but in case it's not accepted I uploaded a [fork with the fix to npm](https://www.npmjs.com/package/fable-react-hot-loader). Hot module replacement is already working for the [react sample](https://github.com/fsprojects/Fable/tree/master/samples/browser/react), just run fable with the `--watch` (or -w) option and `npm start` in another terminal.

I will be updating the documentation for the sample and the usage of the npm released version this weekend :)

**Comment by alfonsogarciacaro** [comment]
Now it's possible to use Babel's [add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) plugin to expose the members of the default export :) Check the last paragraph of [this](https://github.com/fsprojects/Fable/blob/master/docs/compiling.md#modules).

**Comment by alfonsogarciacaro** [comment]
I've finally yielded to reason and now every member of the file root module is exported individually. The generated code will be compatible with tools like react-hot-loader out of the box in the next version :)

**Comment by mastoj** [comment]
Will that also mean it is compatible with react-transform,
https://github.com/gaearon/react-transform-boilerplate, which is the
successor of react-hot-loader?

**Comment by alfonsogarciacaro** [comment]
I had a quick look at that repo before but I didn't understand very well how one is supposed to use the new tool. The README says is highly experimental and the current react-hot-loader is working (there's also an alpha version for 2.0 in npm which works fine too) so I didn't dig deeper :/

**Comment by gaearon** [comment]
There’s some turbulence going on there so I’d suggest staying with RHL for now. We’ll probably merge both projects under RHL brand with a single rewrite I’m working on right now.

**Comment by alfonsogarciacaro** [comment]
Understood, thanks a lot for taking the time to reply, @gaearon!
