### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#76]
I've found an oddity with the JSON.stringify. I was hoping the following 3 classes would yield the same json:

```
type DataR =
    { Id : int
      Name : string }

let dataR =
    { Id = 1
      Name = "Test" }

type DataC1(idBackingFeild, nameBackingField) =
    member x.Id = idBackingFeild
    member x.Name = nameBackingField

let dataC1 = DataC1(1, "test")

type DataC2() =
    member x.Id = 1
    member x.Name = "Test"

let dataC2 = DataC2()

printf "DataR: %s" (JS.Globals.JSON.stringify dataR)
printf "DataC1: %s" (JS.Globals.JSON.stringify dataC1)
printf "DataC2: %s" (JS.Globals.JSON.stringify dataC2)
```

but the result is
```﻿
DataR: {"Id":1,"Name":"Test"}
DataC1: {"idBackingFeild":1,"nameBackingField":"test"}
DataC2: {}
```

**Comment by mastoj** [comment]
I think that makes sense. To be able to deserialize example 2 you must know the name of the arguments to the constructor. And in the last example it doesn't look like instance variables.

**Comment by alfonsogarciacaro** [comment]
This is something that is not documented because I still had some doubts about it. Basically the rules are:

- Records, unions and classes are compiled as ES6 classes; but
- Record fields are actual fields in the JS class (attached to the actual object and **mutable** at runtime). The intention for this is that Records look like a plain old JS object (POJO) but still can be type tested at runtime.
- Class properties translate as getters and setters in the ES6 class, which mean they're **immutable** at runtime (if no setter is defined) and they're attached to the **prototype**. That's why `JSON.stringify` doesn't detect them.

I was thinking to implement the behaviour that `member val Id = 1` properties in classes translate also to fields in the JS object, but I haven't implemented it yet (right now they create an automatic backfield prefixed with `@` which is the default behaviour of the F# compiler). At the moment, you can do this by adding `let mutable Id = 1` to the class constructor, but it's a very hacky solution.

> Tip: if you use `printf "DataR: %A" dataR`, JSON.stringify will be called automatically

**Comment by davidtme** [comment]
I wonder if a [toJSON](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior) function could be automatic added to each class (via an attribute/plugin?) or does anyone know if there is a babel plugin that could do this?

**Comment by alfonsogarciacaro** [comment]
A plugin could be a good way to add this feature but it may be a bit complicated: you have to add the method to the class and then intercept calls to `JSON.stringify` (currently there's no way to do this). Maybe it's easier to just use a JS serialisation library. [Hydrate](http://nanodeath.github.io/HydrateJS/) is a bit older but may do the trick.

**Comment by alfonsogarciacaro** [comment]
Sorry, I didn't check your link, now I see `JSON.stringify` automatically calls the `toJson` method. I understand your proposal much better now. I still need to check if the `toJson` method must be attached to the actual object or it can be put in prototype.

**Comment by davidtme** [comment]
I've got a (hacky) work around:

```
[<Emit("(function(v) { var _objectHelpers = require('./ObjectHelpers.js'); return _objectHelpers.plainObject(v); })($0)" )>]
let inline plainObject value =
    failwith "JS Only"

type DataC1(idBackingFeild, nameBackingField) =
    member x.Id = idBackingFeild
    member x.Name = nameBackingField
    member x.toJSON() : obj = plainObject x
```

ObjectHelpers.js:
```
var ignoreDefaults = ["constructor", "toJSON", "constructor", "toString", "toLocaleString", "valueOf", "hasOwnProperty", "isPrototypeOf", "propertyIsEnumerable", "__defineGetter__", "__lookupGetter__", "__defineSetter__", "__lookupSetter__", "__proto__"];
exports.plainObject = function (value) {
    var objectKeys = Object.keys(value);
    var ignore = ignoreDefaults.concat(objectKeys);
    var keys = []
    for (objectToInspect = value; objectToInspect !== null; objectToInspect = Object.getPrototypeOf(objectToInspect)) {
        keys = keys.concat(Object.getOwnPropertyNames(objectToInspect).filter(function (v) { return ignore.indexOf(v) == -1 }));
    }

    if (keys.length == 0) {
        keys = objectKeys;
    }

    var result = {}
    keys.forEach(function (key) {
        var v = value[key];
        result[key] = typeof v === "object" ? exports.plainObject(v) : v;
    });

    return result;
}
```

**Comment by alfonsogarciacaro** [comment]
It's the solution fine for you then @davidtme? If so, could you please close the issue? Thanks a lot!
