### ISSUE TITLE
Arrays compiled to objects? (Fable 0.1.5)

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#87]
F#: `[| 0; 1; 2; 3 |]` 

is being compiled to 

Js: `{"0":0,"1":1,"2":2,"3":3}`

Is this correct? It shouldn't be compiled to a native array? (`[0, 1, 2, 3]`)

Using the latest version (0.1.5). I didn't work much with arrays until now, so I can't tell if this was happening in the older versions.

**Comment by fdcastel** [comment]
I reverted back to Fable 0.1.4 and can confirm it was working back then (at least for 8 and 16 bit integers).

Sample code:

```
    let a8  = [| 0uy; 1uy; 2uy; 3uy |]
    let a16 = [| 0us; 1us; 2us; 3us |]
    let a32 = [| 0; 1; 2; 3 |]

    a8 |> printfn "%A"
    a16 |> printfn "%A"
    a32 |> printfn "%A"
```

F# output:
```
[|0uy; 1uy; 2uy; 3uy|]
[|0us; 1us; 2us; 3us|]
[|0; 1; 2; 3|]
```

Fable 0.1.4 output:
```
[0,1,2,3]

[0,1,2,3]

{"0":0,"1":1,"2":2,"3":3}
```

Fable 0.1.5 output:
```
{"0":0,"1":1,"2":2,"3":3}

{"0":0,"1":1,"2":2,"3":3}

{"0":0,"1":1,"2":2,"3":3}
```

Shouldn't it map to array in these three cases? (even for 32-bit integers)

**Comment by alfonsogarciacaro** [comment]
You scared me ;) I checked it and arrays are compiled properly (actually, in 0.1.4 byte arrays were not compiled as typed arrays which is fixed now). The problem comes from the print formatting. At the moment, my cheap solution for `%A` formatting is to call `JSON.stringify` [under the hood](https://github.com/fsprojects/Fable/blob/master/src/fable-js/fable-core.js#L318) and apparently this doesn't work well (yet?) with typed arrays. Probably the formatting method needs to be improved in the near future, but at least that seems to be a different problem :)

**Comment by fdcastel** [comment]
Hahahah... APRIL FOOLS!! ;)

(Nah. Just kidding. :) -- I really thought it was bugged. I should've looked at the generated .js file instead of just relying on printfn output).

Thanks! Let's close this one.
