### ISSUE TITLE
Output to ES6? (Possible? Worth it?)

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#89]
It would be possible to output "pure" ES6 code? (instead of "ES5 with some ES6 classes"?)

I know Babel is supposed to translate ES6 to ES5. But... just being curious.:) 

Why?

I'm including the generated .js files in a project written in ES6. And I already have a build pipeline to convert ES6 to ES5. It would be nice to use only one language for everything.

Currently I'm simply importing the Fable-generated files with

`import MyModule from '../imports/MyModule';`

and it works nicely. 

I don't know if this would have any benefit. Just because. ;)

**Comment by alfonsogarciacaro** [comment]
In the next release it will be possible to output ES6 modules to allow tree shaking with tools like WebPack. I wanted to make Fable as easy to use as possible and that's why I'm including the necessary Babel plugins to compile to ES5 by default. But it shouldn't be difficult to add an option to compile to ES6 (ES5 being the default) like TypeScript has, you only need to omit all Babel plugins but the first four (I've found Babel has problems when you don't transform the property mutators):
https://github.com/fsprojects/Fable/blob/master/src/fable-js/index.js#L127-L134

I'll try to do it for the next release :)

**Comment by fdcastel** [comment]
Yeah! After I posted this I did read more about [WebPack 2](https://webpack.github.io/docs/roadmap.html) (currently in beta) planned optimizations and improvements to ES6. Great!

And thanks for the pointers about BabelPlugins. It was extremely valuable for learning more about how Fable works! :+1: 

I will play with them. Let's see.. ;)

**Comment by alfonsogarciacaro** [comment]
This has been also implemented in [the `imports` branch](https://github.com/fsprojects/Fable/blob/imports/src/fable-js/index.js#L27) with the `--ecma` argument :)

> Note: For consistency with `--module` argument, `es2015` must be used instead of `es6` (though we may add `es6` as an alternative).
