### ISSUE TITLE
Suggestion: Move --clamp to plugin?

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#97]
Suggestion: To remove --clamp from Fable and implement it as a plugin?

I'm looking at the significant handling you have to do in build script to test this case. Wouldn't be a better idea to move this to a plugin and to improve the tests for all plugins? It would also simplify the build process.

I don't know how many users of this feature exists out there. It may be a simple change. It may be not. 

Just throwing out the idea. If you agree, I can work on something about it.

**Comment by alfonsogarciacaro** [comment]
This would make a lot of sense. The only problem I see it's the code to compile clamped arrays is so located that adding a plugin check at that point could actually make things more complicated:
https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Fable2Babel.fs#L142

We would probably have to add a plugin hook [when compiling a expression](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Fable2Babel.fs#L280), something I'm reluctant to do because I think it will affect performance to check plugins so often (I haven't tested it, maybe I'm wrong). Another possibility would be to create a Babel plugin instead.

About the test, I changed it in the `imports` branch to make it a referenced project instead of independent scripts. It's still complicated but the main benefit is referenced projects are being tested at the same time :+1:

In any case, yes, it would be nice to add tests for all plugins (whose number has just grown thanks to you). I'd like to add tests for samples too, I still need to check the best way to test UI (as usual in the JS world there're multiple competing options for that).

**Comment by fdcastel** [comment]
I'm closing this suggestion for now. After some tests I believe it would require some extensive changes in the plugin system to make it viable. Not worthy at the moment. ;)
